import { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, ArrowLeft, CheckCircle2, Eye, Flame, Info, Maximize2, Minus, Plus, RotateCcw, Scan, ShieldCheck, User } from "lucide-react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { getPatient } from "../../api/medvisionApi";

const OHIF_URL = process.env.REACT_APP_OHIF_URL || "http://localhost:3001";
const recommendationLibrary = {
  pneumonia: ["Correlate with symptoms, oxygen saturation, and inflammatory markers.", "Arrange clinician or radiologist review; consider follow-up imaging if clinically indicated."],
  tuberculosis: ["Assess symptoms and exposure history; obtain microbiological testing according to local protocol.", "Refer promptly to a TB-capable clinician or service for confirmatory evaluation."],
  "pleural effusion": ["Assess respiratory status and clinical cause; urgent review is needed if breathlessness is significant.", "Consider clinician-directed ultrasound or further imaging to characterize the fluid."],
  pneumothorax: ["Seek urgent clinical assessment, especially with chest pain, breathlessness, or instability.", "Confirm with a qualified clinician or radiologist and manage according to local emergency protocol."],
  cardiomegaly: ["Correlate with cardiac history, examination, and prior imaging.", "Consider clinician-directed cardiovascular assessment if this is new or symptomatic."],
  edema: ["Assess for breathlessness, fluid overload, and cardiac or renal symptoms.", "Prompt clinician review is recommended to correlate with examination and laboratory results."],
  nodule: ["Compare with prior imaging when available and obtain radiologist review.", "Follow local pulmonary nodule guidance for any further imaging or referral."],
  mass: ["Prompt radiologist and treating-clinician review is recommended.", "Compare with prior studies and arrange appropriate diagnostic follow-up."],
  fracture: ["Immobilize and assess pain, function, and neurovascular status as clinically appropriate.", "Arrange clinician or orthopedic review for confirmation and management."],
  "no significant findings": ["No urgent action is suggested by this AI result alone.", "Continue clinical assessment and seek care if symptoms persist or worsen."]
};
const getRecommendations = (finding) => {
  if (Array.isArray(finding.recommendations) && finding.recommendations.length) return finding.recommendations;
  const key = Object.keys(recommendationLibrary).find((item) => (finding.name || "").toLowerCase().includes(item));
  return key ? recommendationLibrary[key] : ["Have this finding reviewed in the context of the patient’s symptoms and history.", "Use a qualified clinician or radiologist to confirm the result and determine follow-up."];
};
const formatDate = (value) => { if (!value) return "Not recorded"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }); };
const confidenceLabel = (value) => value >= 85 ? "High confidence" : value >= 60 ? "Moderate confidence" : "Lower confidence";

export default function DiagnosticResults() {
  const navigate = useNavigate(); const location = useLocation(); const { patientId } = useParams(); const viewerRef = useRef(null);
  const [patientData, setPatientData] = useState(null); const [loading, setLoading] = useState(true);
  const [showHeatmap, setShowHeatmap] = useState(true); const [heatmapOpacity, setHeatmapOpacity] = useState(62); const [zoom, setZoom] = useState(1); const [selectedFinding, setSelectedFinding] = useState(null);
  useEffect(() => {
    let cancelled = false;
    const load = async () => {
      if (patientId) { try { const patient = await getPatient(patientId); if (!cancelled) setPatientData(patient); } catch (error) { console.error("Unable to load saved patient:", error); if (!cancelled) setPatientData(location.state?.patientData || null); } finally { if (!cancelled) setLoading(false); } return; }
      if (location.state?.patientData) setPatientData(location.state.patientData);
      else if (location.state?.aiData && location.state?.formData) setPatientData({ ...location.state.formData, aiFindings: Array.isArray(location.state.aiData) ? location.state.aiData : [location.state.aiData], heatmapUrl: location.state.heatmapUrl });
      else navigate("/");
      if (!cancelled) setLoading(false);
    }; load(); return () => { cancelled = true; };
  }, [patientId, location.state, navigate]);
  const originalSrc = useMemo(() => patientData?.imageUrl || (patientData?.image ? URL.createObjectURL(patientData.image) : null), [patientData]);
  useEffect(() => () => { if (originalSrc?.startsWith("blob:")) URL.revokeObjectURL(originalSrc); }, [originalSrc]);
  if (loading || !patientData) return <div className="min-h-screen grid place-items-center bg-slate-950 text-slate-300">Loading diagnostic workspace…</div>;
  const findings = Array.isArray(patientData.aiFindings) ? patientData.aiFindings : [];
  const studyInstanceUID = patientData.studyInstanceUID || patientData.study_instance_uid || patientData.dicom?.study_instance_uid;
  const isDicom = String(patientData.sourceFormat || patientData.source_format || "").toLowerCase() === "dicom" || Boolean(studyInstanceUID);
  const activeFinding = selectedFinding === null ? findings[0] : findings[selectedFinding];
  const hasHeatmap = Boolean(patientData.heatmapUrl) && findings.some((item) => item.name !== "No Significant Findings");
  const adjustZoom = (amount) => setZoom((current) => Math.max(.75, Math.min(1.75, +(current + amount).toFixed(2))));
  return <div className="min-h-screen bg-[#08111f] text-slate-100">
    <header className="sticky top-0 z-20 border-b border-slate-700/70 bg-[#0c1728]/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-[1800px] items-center justify-between px-4 sm:px-6"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-cyan-400 text-slate-950"><Scan size={20}/></div><div><h1 className="font-semibold tracking-tight">MedVision AI</h1><p className="text-xs text-slate-400">Diagnostic workspace</p></div></div><div className="hidden items-center gap-3 sm:flex"><span className="rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1 text-xs font-medium text-emerald-300">● Analysis complete</span><Link to="/" className="text-sm text-slate-300 hover:text-white">New analysis</Link></div></div></header>
    <main className="mx-auto max-w-[1800px] p-4 sm:p-6">
      <div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><button onClick={() => navigate(-1)} className="mb-2 flex items-center gap-1 text-sm text-slate-400 hover:text-white"><ArrowLeft size={15}/> Back to studies</button><h2 className="text-xl font-semibold">Chest X-ray analysis</h2><p className="mt-1 text-sm text-slate-400">{patientData.name || "Unnamed patient"} <span className="mx-1">•</span> {patientData.patientId || "No patient ID"} <span className="mx-1">•</span> {formatDate(patientData.date)}</p></div><div className="flex items-center gap-2 text-xs text-slate-400"><ShieldCheck size={16} className="text-cyan-300"/> AI-assisted decision support — not a final diagnosis</div></div>
      <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_370px]">
        <section className="min-w-0 overflow-hidden rounded-2xl border border-slate-700/80 bg-[#101c2e] shadow-2xl shadow-black/20">
          <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-700/70 px-4 py-3"><div className="flex items-center gap-3"><div className="rounded-lg bg-cyan-400/10 p-2 text-cyan-300"><Scan size={18}/></div><div><h3 className="font-medium">{isDicom ? "DICOM image viewer" : "Medical image viewer"}</h3><p className="text-xs text-slate-400">{patientData.scanType || "Chest X-ray"} · Frontal view</p></div></div><div className="flex items-center gap-1 rounded-lg border border-slate-700 bg-slate-900/70 p-1"><button onClick={() => adjustZoom(-.1)} title="Zoom out" className="rounded p-1.5 text-slate-300 hover:bg-slate-700"><Minus size={17}/></button><span className="w-12 text-center text-xs text-slate-400">{Math.round(zoom * 100)}%</span><button onClick={() => adjustZoom(.1)} title="Zoom in" className="rounded p-1.5 text-slate-300 hover:bg-slate-700"><Plus size={17}/></button><button onClick={() => setZoom(1)} title="Reset zoom" className="rounded p-1.5 text-slate-300 hover:bg-slate-700"><RotateCcw size={16}/></button><button onClick={() => viewerRef.current?.requestFullscreen?.()} title="Fullscreen" className="rounded p-1.5 text-slate-300 hover:bg-slate-700"><Maximize2 size={16}/></button></div></div>
          <div ref={viewerRef} className="relative flex min-h-[500px] items-center justify-center overflow-hidden bg-[#05090f] sm:min-h-[620px]">{isDicom ? <iframe title="MedVision DICOM Viewer" src={studyInstanceUID ? `${OHIF_URL}/viewer?StudyInstanceUIDs=${encodeURIComponent(studyInstanceUID)}` : OHIF_URL} className="h-[620px] w-full border-0" allow="fullscreen"/> : originalSrc ? <div className="relative flex h-full w-full items-center justify-center overflow-hidden"><img src={originalSrc} alt="Uploaded chest radiograph" className="max-h-[620px] max-w-full object-contain transition-transform duration-200" style={{ transform: `scale(${zoom})` }}/>{hasHeatmap && showHeatmap && <img src={patientData.heatmapUrl} alt="AI attention heatmap" className="pointer-events-none absolute max-h-[620px] max-w-full object-contain mix-blend-screen" style={{ opacity: heatmapOpacity / 100, transform: `scale(${zoom})` }}/>}<div className="absolute left-4 top-4 rounded bg-black/70 px-2 py-1 font-mono text-xs text-white">R</div><div className="absolute right-4 top-4 rounded bg-black/70 px-2 py-1 text-xs text-slate-200">{patientData.scanType || "XR CHEST"}</div></div> : <div className="text-center text-slate-500"><Scan className="mx-auto mb-3" size={36}/><p>No image available for this study.</p></div>}</div>
          {hasHeatmap && !isDicom && <div className="flex flex-wrap items-center justify-between gap-4 border-t border-slate-700/70 bg-slate-900/40 px-4 py-3"><div className="flex items-center gap-2"><Flame size={17} className="text-orange-400"/><span className="text-sm font-medium">AI attention heatmap</span><button onClick={() => setShowHeatmap(!showHeatmap)} className={`ml-2 rounded-md px-3 py-1.5 text-xs font-medium ${showHeatmap ? "bg-cyan-400 text-slate-950" : "bg-slate-700 text-slate-200"}`}>{showHeatmap ? "Visible" : "Hidden"}</button></div><label className="flex items-center gap-3 text-xs text-slate-400"><span>Opacity</span><input aria-label="Heatmap opacity" type="range" min="10" max="100" value={heatmapOpacity} onChange={(e) => setHeatmapOpacity(Number(e.target.value))} className="accent-cyan-400"/><span className="w-7 text-right">{heatmapOpacity}%</span></label></div>}
        </section>
        <aside className="space-y-5"><section className="rounded-2xl border border-slate-700/80 bg-[#101c2e] p-5"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><AlertTriangle size={19} className="text-amber-300"/><h3 className="font-semibold">AI findings</h3></div><span className="text-xs text-slate-400">{findings.length} detected</span></div><div className="space-y-2">{findings.length ? findings.map((finding, index) => { const probability = Number(finding.probability || 0); const selected = selectedFinding === null ? index === 0 : selectedFinding === index; return <button key={`${finding.name}-${index}`} onClick={() => setSelectedFinding(index)} className={`w-full rounded-xl border p-3 text-left transition ${selected ? "border-cyan-400/70 bg-cyan-400/10" : "border-slate-700 bg-slate-900/40 hover:border-slate-500"}`}><div className="flex items-start justify-between gap-3"><div><p className="font-medium text-slate-100">{finding.name || "Unknown finding"}</p><p className="mt-1 text-xs text-slate-400">{confidenceLabel(probability)}</p></div><span className="font-semibold text-cyan-300">{probability.toFixed(probability % 1 ? 1 : 0)}%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-700"><div className="h-full rounded-full bg-cyan-400" style={{ width: `${Math.min(100, probability)}%` }}/></div></button>; }) : <p className="rounded-xl bg-slate-900/40 p-4 text-sm text-slate-400">No AI findings are available yet.</p>}</div></section>
          <section className="rounded-2xl border border-slate-700/80 bg-[#101c2e] p-5"><div className="mb-4 flex items-center gap-2"><CheckCircle2 size={19} className="text-emerald-400"/><h3 className="font-semibold">Recommendation</h3></div>{activeFinding ? <><p className="mb-3 text-sm font-medium text-cyan-200">For {activeFinding.name}</p><ul className="space-y-3">{getRecommendations(activeFinding).map((item, index) => <li key={index} className="flex gap-2 text-sm leading-5 text-slate-300"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-400"/>{item}</li>)}</ul></> : <p className="text-sm text-slate-400">Select a finding to view contextual recommendations.</p>}<div className="mt-5 rounded-lg border border-amber-400/15 bg-amber-300/5 p-3 text-xs leading-5 text-amber-100/80"><Info size={14} className="mr-1 inline text-amber-300"/> Recommendations support clinical review and do not replace a qualified medical assessment.</div></section></aside>
      </div>
      <section className="mt-5 grid gap-5 lg:grid-cols-[1fr_2fr]"><div className="rounded-2xl border border-slate-700/80 bg-[#101c2e] p-5"><div className="mb-4 flex items-center gap-2"><User size={18} className="text-cyan-300"/><h3 className="font-semibold">Study details</h3></div><dl className="grid grid-cols-2 gap-x-5 gap-y-3 text-sm"><div><dt className="text-xs text-slate-500">Patient</dt><dd className="mt-0.5 text-slate-200">{patientData.name || "Not recorded"}</dd></div><div><dt className="text-xs text-slate-500">Age / sex</dt><dd className="mt-0.5 text-slate-200">{patientData.age || "—"} / {patientData.gender || "—"}</dd></div><div><dt className="text-xs text-slate-500">Study date</dt><dd className="mt-0.5 text-slate-200">{formatDate(patientData.date)}</dd></div><div><dt className="text-xs text-slate-500">Modality</dt><dd className="mt-0.5 text-slate-200">{patientData.dicom?.modality || "X-ray"}</dd></div></dl></div><div className="rounded-2xl border border-slate-700/80 bg-[#101c2e] p-5"><div className="mb-3 flex items-center gap-2"><Eye size={18} className="text-cyan-300"/><h3 className="font-semibold">Interpretation note</h3></div><p className="text-sm leading-6 text-slate-400">The heatmap highlights image regions that influenced the model’s output. It does not identify a diagnosis by itself and should be interpreted alongside the full image, clinical history, and a radiologist’s report.</p></div></section>
    </main>
  </div>;
}
